### ISSUE TITLE
Two great online books

### ISSUE THREAD

**Issue by tomek-he-him** [deanhume/typography#3]
Both freely available for reading (though [not free](http://practicaltypography.com/how-to-pay-for-this-book.html)).
- http://practicaltypography.com/  
  a fantastic, involving read!
- http://webtypography.net/  
  not as captivating – but very professionally written

/cc @mbutterick

**Comment by deanhume** [comment]
Ill get this added - thank you!

**Comment by deanhume** [comment]
Updated - thanks!
