### ISSUE TITLE
Add this!

### ISSUE THREAD

**Issue by deanhume** [deanhume/typography#4]
Adds OpenType features—ligatures, kerning, and more—to Normalize.css.
https://github.com/kennethormandy/normalize-opentype.css

**Comment by deanhume** [comment]
And this - http://blog.spoongraphics.co.uk/articles/a-history-of-typeface-styles-type-classification

and this - https://medium.com/product-design-ux-ui/26-digital-typography-rules-for-beginners-a04c6a5aaff3

**Comment by deanhume** [comment]
and this - http://alistapart.com/blog/post/variable-fonts-for-responsive-design

and this - http://www.frerejones.com/blog/typeface-mechanics-001/

**Comment by deanhume** [comment]
Add this under tools - https://blot.im/typeset/

**Comment by thebox-newsuk** [comment]
Nice

**Comment by deanhume** [comment]
Add this too! http://blog.spoongraphics.co.uk/articles/the-best-free-alternatives-to-the-most-popular-fonts
